development:
  amadeus_client_id:
  amadeus_client_secret:
  nytimes_api_key:
  DB_FILENAME:
  SESSION_SECRET:
  API_HOST: http://localhost:9090
  APP_HOST: http://localhost:9000

test:
  amadeus_client_id: 
  amadeus_client_secret: 
  nytimes_api_key: 
  DB_FILENAME: 
  SESSION_SECRET:
  API_HOST: http://localhost:9090
  APP_HOST: http://localhost:9000

production:
  amadeus_client_id: 
  amadeus_client_secret: 
  nytimes_api_key: 
  DB_FILENAME: 
  SESSION_SECRET:
  API_HOST:
  APP_HOST: